---
# yamllint disable rule:line-length
# yamllint disable rule:trailing-spaces
global:
  # Required by slack_configs
  slack_api_url: {{ .Env.SLACK_API_URL }}
receivers:
  # User defined receivers
{{ include "conf/*/receivers.yml" . | indent 2 }}
route:
  # Required by default
  receiver: receiver
  routes:
    # User defined routes
{{ include "conf/*/routes.yml" . | indent 4 }}
