language: go

go:
  - "1.14"

script:
  - wget https://github.com/prometheus/alertmanager/releases/download/v0.21.0/alertmanager-0.21.0.linux-amd64.tar.gz
  - tar zxvf alertmanager-0.21.0.linux-amd64.tar.gz
  - sudo mv alertmanager-0.21.0.linux-amd64/amtool /usr/local/bin/
  - go test -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
